NRI課題(1)を追加しました。
masayoshixxx/codegym-html pull request #1
Opened 2021-04-10 07:04 UTC by masayoshixxx

2021-04-12 11:49 UTC, Yuzunoha commented
(修正不要です)
慣れてきたらコミットをもっと細かくするように意識してみましょう。
例えば
・誤字脱字の修正のみを行った
・セクションの順序の変更のみを行った
という具合にコミットが小さく分かれていた方が管理する上で便利です。

2021-04-12 11:50 UTC, Yuzunoha commented on nri/index.html
> +            <a class="botton" href="#">NRIのデジタルトランスフォーメーション</a>
クラス名がタイポしていますね

2021-04-12 11:51 UTC, Yuzunoha commented on nri/index.html
> +            <a class="botton" href="#">NRIのデジタルトランスフォーメーション</a>
あと
（7.43 MB）
とpdfのsvgアイコンが無いですね

pdfのsvgアイコンは本家から取れなければ、似ているやつをネットから拾ってくればよいです

2021-04-12 11:59 UTC, masayoshixxx commented on nri/index.html
> +            <a class="botton" href="#">NRIのデジタルトランスフォーメーション</a>
ユズノハさんありがとうございます。
本家からスクショで直して再提出させていただきます。
スペルミスもありがとうございます！

今回間違えてデスクトップに「nri」というフォルダを作成して作ってしまい、提出の段階でgitフォルダに作成するものと知ったためコミットが一括になっていまいました。次回からコミット細かめで作成します！

2021-04-12 12:05 UTC, Yuzunoha commented on nri/index.html
> +                <li><a href="#">NRIグループの企業行動原理</a></li>
```suggestion

                <li><a href="#">NRIグループ企業行動原則</a></li>
```

2021-04-12 12:06 UTC, Yuzunoha commented on nri/index.html
> +                <li><a href="#">その他の関連会社</a></li>
```suggestion
                <li><a href="#">その他の関連会社・団体</a></li>
```

2021-04-12 12:07 UTC, Yuzunoha commented on nri/index.html
> +              <li class="black-2"><a href="#">ナレッジインサイト</a></li>
```suggestion
              <li class="black-2"><a href="#">ナレッジ・インサイト</a></li>
```

2021-04-12 12:08 UTC, Yuzunoha commented on nri/index.html
> +                <li><a href="#">未来開発センター</a></li>
```suggestion
                <li><a href="#">未来創発センター</a></li>
```

2021-04-12 12:08 UTC, Yuzunoha commented on nri/index.html
> +                <li><a href="#">サスティナビリティマネジメント</a></li>
```suggestion
              <li class="black-2"><a href="#">サステナビリティ</a></li>
                <li><a href="#">サステナビリティマネジメント</a></li>
```

2021-04-12 12:12 UTC, Yuzunoha requested changes
いったんお返しします！
文言はタイピングせずに本家からコピペしたほうがよいですよっ

例えば

`未来創発センター`

を間違えて

`未来開発センター`

にしてしまうとお客さんが怒ります 笑。

2021-04-13 12:47 UTC, kai-kou commented
ユズノハさん指摘については修正できていることが確認できました。

2021-04-13 12:49 UTC, kai-kou commented
Shareリンクについて一番うえのものが実装されていませんでした。

<img width="1063" alt="スクリーンショット 2021-04-13 21 47 01" src="https://user-images.githubusercontent.com/41495183/114554717-fccea180-9ca1-11eb-9f39-1bce5edfc64e.png">

2021-04-13 12:57 UTC, kai-kou commented
[ユズノハさんの指摘](https://github.com/masayoshixxx/codegym-html/pull/1#discussion_r611560616)に対して
>あと
>（7.43 MB）
>とpdfのsvgアイコンが無いですね

本来であればpdfのマークがないですよ。という指摘でしたが、ボタンまるごとを画像としているのは良しとして、この実装の場合、`<img src="images/pdf.png" alt="ボタン">`と`<a class="button" href="#">NRIのデジタルトランスフォーメーション</a>`の2つのボタン(リンク)が存在することになってしまいますので、1つにまとめてください。

https://github.com/masayoshixxx/codegym-html/blob/566c7aa469c409354c142b2b48b0a5f9177f4fe4/nri/index.html#L51-L55

2021-04-15 12:17 UTC, TomoakiTANAKA commented
レビューメモ

- [x] htmlチェッカー
- [ ] 画像過不足
- [ ] テキスト過不足
- [ ] その他指摘事項

2021-04-15 12:56 UTC, TomoakiTANAKA commented on nri/index.html
> +              「DX1.0」、デジタルで新しいビジネスモデルそのものを生み出す DX を「DX2.0」と定義しています。
めちゃくちゃ細かいのですが、「を」の後に改行がはいっていることで本番とテキストが一致していません。
修正をお願いします。

（本番のテキストをコピーして、こちらのコードに貼り付けたらヒットしなかった、という調べ方で発見しています。）

```suggestion
              NRI では、企業の DX に向けた取り組みについて、既存ビジネスの業務プロセス変革に寄与する DX を           「DX1.0」、デジタルで新しいビジネスモデルそのものを生み出す DX を「DX2.0」と定義しています。
```

2021-04-15 12:56 UTC, TomoakiTANAKA commented on nri/index.html
> +          </div>
info（修正不要）

「<」と「>」部分が実物ではテキストなのでできれば踏襲する形がいいかなと思います。
cssで表現してもOKですので、修正不要の指摘としています。

他にも「<」のような部分があるのですが、ここだけテキストなんですよね…

2021-04-15 12:56 UTC, TomoakiTANAKA commented on nri/index.html
> +            <div class="item"><a href="#">業界トップクラスの集客力</a></div>
「NRIの強み」という情報に対して、強みの一つはこれ、も一つはこれ、と説明しているブロックです。

このような場合は、divを使うよりも箇条書き（ul > li）を使うのがよりよいです。
※本ちゃんのサイトはdivですね…w

```suggestion
            <p>NRIの強み</p>
            <ul>
              <li class="item"><a href="#">NRIのあゆみと持続的な成長</a></li>
              <li class="item"><a href="#">問題発見から問題解決まで</a></li>
              ..以下略
            </ul>              
```

2021-04-15 12:56 UTC, TomoakiTANAKA commented on nri/index.html
> +            <h3 class="white-1">NRIの強み</h3>
見出しタグは、h1の中にh2、h2の中にh3という形にするのが基本です。
なので、今回のコードの形式でいえばh2が正しいです。

なお、h1を複数使うのはOKです。
こんな形はOK

```
h1
  h2
    h3
  h2
    h3
h1
  h2
...
```

2021-04-15 12:58 UTC, TomoakiTANAKA commented on nri/index.html
>            </div><!--/.link-wrapper-->
aタグを削除したことで、周りのdivタグも不要になっていると思います。
不要であればまとめて削除しましょう、

2021-04-17 01:01 UTC, TomoakiTANAKA commented on nri/index.html
> +            <p><<a href="#">ビジネスモデルの特徴</a></p>
`<`は特殊な文字です。（タグの開始文字として間違われてしまう）
通常、`&lt;`などを利用しますので修正をお願いします。

「HTML エスケープ 文字」
「HTML　特殊文字」

などでググるとヒントがでてきます。もし知識に不安がある場合は、調べて見てください。

http://www.eonet.ne.jp/~usakuma/hptec/hp_tec/hptec_style_41.htm

2021-04-17 01:03 UTC, TomoakiTANAKA commented on nri/index.html
> +            <li class="item"><a href="#">業界トップクラスの集客力</a></li>
ulタグの使い方が違うので、修正してください。
また、修正の際にインデントも下記のように修正してください。

箇条書きのアイテムを`まとめる`タグです。
なので、liを囲む形で記述します。

```html
<ul>
  <li>....</li>
  <li>....</li>
</ul>
```

2021-04-17 01:04 UTC, TomoakiTANAKA commented on nri/index.html
> +            <p>＜<a href="#">ビジネスモデルの特徴</a></p>
`<`は特殊な文字です。（タグの開始文字として間違われてしまう）
また、全角文字を使ってもコード上では紛らわしいので、通常、`&lt;`などを利用します。

修正をお願いします。

「HTML エスケープ 文字」
「HTML　特殊文字」

などでググるとヒントがでてきます。もし知識に不安がある場合は、調べて見てください。

http://www.eonet.ne.jp/~usakuma/hptec/hp_tec/hptec_style_41.htm

2021-04-17 01:09 UTC, TomoakiTANAKA commented
## レビューメモ

- [ ]  htmlチェッカー：OK
- [ ]  画像過不足：NG（画像は存在するが、タグがない）
- [ ]  テキスト過不足：OK
- [ ]  その他指摘事項：コード参照

画像が内容です

![image](https://user-images.githubusercontent.com/1779811/115097387-ddb36680-9f64-11eb-9696-b1c086edbfcb.png)

2021-04-17 01:18 UTC, TomoakiTANAKA commented on nri/index.html
> +          <ul class="log">
typoですかね？logoのような

```suggestion
          <ul class="logo">
```

2021-04-17 01:18 UTC, TomoakiTANAKA commented on nri/index.html
> +          <ul class="log">
このあたりに実際のサイトではsnsシェアのタグあります。
記事下部に追加してくれているタグを参考に、こちらにもタグを設定してください。
![image](https://user-images.githubusercontent.com/1779811/115097387-ddb36680-9f64-11eb-9696-b1c086edbfcb.png)

2021-04-17 01:19 UTC, TomoakiTANAKA commented
## レビューメモ

- [ ]  htmlチェッカー：OK
- [ ]  画像過不足：NG（画像は存在するが、タグがない）
- [ ]  テキスト過不足：OK
- [ ]  その他指摘事項：コード参照

2021-04-17 01:29 UTC, masayoshixxx commented on nri/index.html
> +          <ul class="log">
logoはもう使用していたのでlistに変更しました。
記録みたいな意味でlogにしてましたが紛らわしいですね...

2021-04-17 01:32 UTC, masayoshixxx commented on nri/index.html
> +            <li class="item"><a href="#">業界トップクラスの集客力</a></li>
確認したのですが60の行あたりは<ul>で囲まれているように見えます。
一旦プッシュしてみます。

2021-04-17 02:23 UTC, TomoakiTANAKA commented on nri/index.html
> +            <li class="item"><a href="#">業界トップクラスの集客力</a></li>
すみません。なにかとの勘違いでした。
このコードでOKです。

2021-04-17 02:24 UTC, TomoakiTANAKA commented
SNSシェアが1つしかないです。ページ上部と下部の2箇所にあります。
追加ください。
![Uploading image.png…]()

2021-04-17 05:39 UTC, disneyLadySango reviewed
@masayoshixxx 
お疲れ様です、こちら何点かコメントしました！
次の課題でこのままだと苦戦しそう・・・と思った点もコメント入れましたので、是非こちらも次のCSS課題のために対応していただければと思います！

LGTMまで後一歩だと思います頑張りましょう！

2021-04-17 05:39 UTC, disneyLadySango commented on nri/index.html
> +          <a href="#"><img src="images/linkedin.png" alt="リンクトイン"></a>
[should]
この後のCSS課題でおそらく修正入れなければいけない時がくると思うので先にコメントだけ入れておきます

この書き方だとスタイルを当てづらいと思うので、

```
<div>
  <p>Share</p>
  <a href="#"><img src="images/facebook.png" alt="フェイスブック"></a>
  <a href="#"><img src="images/twitter.png" alt="ツイッター"></a>
  <a href="#"><img src="images/linkedin.png" alt="リンクトイン"></a>
</div>
```

で囲ってあげとくと良いです！
HTMLは文章というのを意識してもらえると良いのですが、
ここのShareボタン郡は一つの構造になっているのでそういう時は`div`などで囲ってあげると良いです！

2021-04-17 05:39 UTC, disneyLadySango commented on nri/index.html
> +            <a href="#"><img src="images/pdf.png" alt="ボタン"></a>
[must]
こちらはマストですいません🙇‍♂️
ここのボタン要素課題的には
`PDFのアイコンは画像を拾ってくるかスクショでOK`それ以外はHTMLでマークアップして欲しいという意図かと思います。
ここを綺麗に並べられるかというのもまた次のCSS課題の項目の一つかと思うので是非ご対応いただけると嬉しいです！

なのでボタンに丸々画像を挿入せずにアイコンの部分だけ画像を挿入する形にしてもらえますでしょうか？
こんなイメージです

```
<a href="#">
  NRIのデジタルトランスフォーメーション(7.43MB)
  <img src="images/icon-pdf.png" alt="pdf" />
</a>
```

また上の例ではあえて記載していないのですが、`NRIのデジタルトランスフォーメーション`と`(7.43MB)`の間に改行も入れてください

2021-04-17 05:39 UTC, disneyLadySango commented on nri/index.html
> +          <a href="#"><img src="images/linkedin.png" alt="リンクトイン"></a>
[should]
こちらもCSS課題を考えると`div`で囲っておくと良いかと思います！

2021-04-17 05:39 UTC, disneyLadySango commented on nri/index.html
> +                <li><a href="#">社長メッセージ</a></li>
[must]
この辺りインデントが揃っていないようなのでご対応お願いします
```
NG
<li class="black">経営方針</li>
  <li><a href="#">社長メッセージ</a></li>

OK
<li class="black">経営方針</li>
<li><a href="#">社長メッセージ</a></li>
```

2021-04-17 06:37 UTC, disneyLadySango approved these changes
@masayoshixxx 
LGTMです！！！！
ご対応ありがとうございました！！！
１個だけ細かいコメント入れましたがこちらは再レビューは不要ですので
対応後次の課題にうつりましょう！
お疲れ様でした！

2021-04-17 06:37 UTC, disneyLadySango commented on nri/index.html
> +                <img src="images/pdf.png" alt="pdf">
[good]
ご対応ありがとうございます！！！
綺麗なコードでとても良いです！

2021-04-17 06:37 UTC, disneyLadySango commented on nri/index.html
> +          <a href="#"><img src="images/linkedin.png" alt="リンクトイン"></a>
[should]
ここもShareと同じく`div`で囲っておくと次の課題のときに楽です！
とは言え、こちら再レビュー不要ですので、修正コミットしたらレビュー依頼せずマージしてOKです！

2021-04-26 12:37 UTC, merged